baseurl: 'https://sa.sasasa.org/'
title: 'sasasa'
source: ''
name: 'sasasa'
dst: '_site/'
posts: '_posts/'
pages: '_pages/'
tags: '_tags/'
assets: '_assets/'
data: '_assets/data/'
css: '_assets/css/'
js: '_assets/js/'
img: '_assets/img/'
watch: ["./_posts", "./_pages", "./_tags", "_layouts", "./_assets/css", "./_assets/js", "./_assets/img"]
includes: ''
layouts: '_layouts'
permalink: ''
exclude: ['']
host: 'localhost'
port: 9898
markdown_ext: '.md'

